### ISSUE TITLE
Foxes replaces player and doesnt despawn when player rejoins

### ISSUE THREAD

**Issue by J-dotjs** [derfurkan/OfflinePlayers#5] opened 2023-06-04 03:11 UTC
Server Version: Spigot 1.19.4
Console logs: not relevant
Spigot or Bukkit: Spigot
Using a fork or original: Original
What plugins: BreakTogether, CropsPlus, DiscordChatMonitor, dualhorse, EnchantsSquared, Graves, LibsDisguises, mydog, OfflinePlayers, OldCOmbatMechanics, ProtocolLib, ValorlessUtils
Which version of OfflinePlayers and LibsDisguises: 2.2, 10.0.35
Your config.yml file: 
```
#Welcome to OfflinePlayers
#This Plugin spawns a clone from a Player if he is offline at his logout location!
#Here you can configure the plugin and the behavior of the offline clones.

OfflinePlayer:
  cloneEntity: PLAYER #The entity type of the clone. You can find a list of all entity types here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  cloneRawEntity: FOX #The raw entity type that will be used to create an undisguised clone. This entity will be disguised with the cloneEntity.
  cloneSpawnDistance: 50 #The range in blocks a player has to be in to show a clone.
  cloneUpdateTimer: 15 #The value in ticks that defines in which interval the clone's visible state is updated. (20 ticks = 1 second)
  cloneItemPickup: true #If true the clones will be able to pick up items.
  cloneIsHittable: false #If the clone is damageable.
  cloneHasAI: true #If true the clone is able to be fall down, pushed or knocked back.
  cloneName: "§8§lOffline §7- §c%PLAYER_NAME" #The name of the clone. %PLAYER_NAME will be replaced with the name of the player. %DESPAWN_TIMER% will be replaced with the time until the clone despawns.
  cloneDe-spawnTimer:
    enabled: false
    timer: 20 #The time in seconds the clone is de-spawned after it is spawned.
  game-modeBlacklist: #A list of gamemodes where the clones will not spawn.
    - CREATIVE
    - SPECTATOR
  worldBlacklist: #A list of worlds where the clones will not spawn.
    - world1
    - world2
    - world3
  permissions: #If enabled players will only get a clone if they have the permission.
    enabled: false
    permission: 'offlineplayer.clone'
```
etc. (Every bit of information that you might think is relevant in fixing the issue)
    Happens on server restart, player is offline for a long time, despawn timer is off, and everytime i relog

**Comment by derfurkan** [comment] 2023-06-04 03:31
When you restart the server do you force kill it or do you use the /stop command?
The plugin does not save clones on reload/restart so it deletes them if a shutdown/reload is called. 
If the server is killed most plugins don't have time to run their shutdown logic.

**Comment by J-dotjs** [comment] 2023-06-04 16:22
> When you restart the server do you force kill it or do you use the /stop command?
> The plugin does not save clones on reload/restart so it deletes them if a shutdown/reload is called. 
> If the server is killed most plugins don't have time to run their shutdown logic. 

It happens without restarting the server like I said

**Comment by derfurkan** [comment] 2023-06-04 23:13
Would you give me steps on how to reproduce this problem?
I guess there are no console errors since your said they are not relevant.

Have you ever changed some settings in the bukkit or spigot YAML files that manipulates the behavior of entities or chunks or any other `plugin/setting/datapack` that manipulate how entities or chunks behave?

**This can happen when OfflinePlayers clears its map where every clone is saved or if LibsDisguises Undisguises an entity.**
If this happens again you can walk 60 Blocks away from the fox and come back to see if another clone has been created.

### My approach to fix this issue is by listening to the `UndisguiseEvent` and disguise the clone right after. But to ensure this will work i need to reproduce this problem.

**Comment by J-dotjs** [comment] 2023-06-05 00:10
What I did was I started a clean slate with the same plugins reinitiated the server and the plugins, change the YAML file to what I put in the original post, I changed nothing but the config for this plugin, then I joined the server, my friend joined, I left, they left a little after, I join after 30 ish minutes I have a fox at my feet AND my friend has their player skin AND the fox at their feet as well

**Comment by J-dotjs** [comment] 2023-06-05 00:10
> What I did was I started a clean slate with the same plugins reinitiated the server and the plugins, change the YAML file to what I put in the original post, I changed nothing but the config for this plugin, then I joined the server, my friend joined, I left, they left a little after, I join after 30 ish minutes I have a fox at my feet AND my friend has their player skin AND the fox at their feet as well

I can record it happening if needed

**Comment by derfurkan** [comment] 2023-06-05 07:11
> > What I did was I started a clean slate with the same plugins reinitiated the server and the plugins, change the YAML file to what I put in the original post, I changed nothing but the config for this plugin, then I joined the server, my friend joined, I left, they left a little after, I join after 30 ish minutes I have a fox at my feet AND my friend has their player skin AND the fox at their feet as well
> 
> I can record it happening if needed

Yes would you do that please.
Also i tried to reproduce the issue and everything worked fine on my side. Are you sure you are not missing something?

**Comment by J-dotjs** [comment] 2023-06-05 23:26
> > > What I did was I started a clean slate with the same plugins reinitiated the server and the plugins, change the YAML file to what I put in the original post, I changed nothing but the config for this plugin, then I joined the server, my friend joined, I left, they left a little after, I join after 30 ish minutes I have a fox at my feet AND my friend has their player skin AND the fox at their feet as well
> > 
> > I can record it happening if needed
> 
> Yes would you do that please.
> Also i tried to reproduce the issue and everything worked fine on my side. Are you sure you are not missing something?

I'll get that recording as soon as I can, did you put the same plugins I stated in your server? Could another plugin be interfering with it? Not entirely sure tho because none of my plugins have anything to do with the disguises or this plugin

**Comment by derfurkan** [comment] 2023-06-06 05:47
> > > > What I did was I started a clean slate with the same plugins reinitiated the server and the plugins, change the YAML file to what I put in the original post, I changed nothing but the config for this plugin, then I joined the server, my friend joined, I left, they left a little after, I join after 30 ish minutes I have a fox at my feet AND my friend has their player skin AND the fox at their feet as well
> > > 
> > > 
> > > I can record it happening if needed
> > 
> > 
> > Yes would you do that please.
> > Also i tried to reproduce the issue and everything worked fine on my side. Are you sure you are not missing something?
> 
> I'll get that recording as soon as I can, did you put the same plugins I stated in your server? Could another plugin be interfering with it? Not entirely sure tho because none of my plugins have anything to do with the disguises or this plugin

You might be right that a plugin of your server interfere with OfflinePlayers.
You can try disabling every plugin and enabling it one by one until the issue appears again.

All i can say is that its most likely not a bug in OfflinePlayers.

**Comment by J-dotjs** [comment] 2023-06-09 02:51
> > > > > What I did was I started a clean slate with the same plugins reinitiated the server and the plugins, change the YAML file to what I put in the original post, I changed nothing but the config for this plugin, then I joined the server, my friend joined, I left, they left a little after, I join after 30 ish minutes I have a fox at my feet AND my friend has their player skin AND the fox at their feet as well
> > > > 
> > > > 
> > > > I can record it happening if needed
> > > 
> > > 
> > > Yes would you do that please.
> > > Also i tried to reproduce the issue and everything worked fine on my side. Are you sure you are not missing something?
> > 
> > 
> > I'll get that recording as soon as I can, did you put the same plugins I stated in your server? Could another plugin be interfering with it? Not entirely sure tho because none of my plugins have anything to do with the disguises or this plugin
> 
> You might be right that a plugin of your server interfere with OfflinePlayers. You can try disabling every plugin and enabling it one by one until the issue appears again.
> 
> All i can say is that its most likely not a bug in OfflinePlayers.

after further testing, it still happens with it being the only plugin on the server

**Comment by J-dotjs** [comment] 2023-06-09 03:01
![image](https://github.com/derfurkan/OfflinePlayers/assets/87219200/10788752-8b0b-4b65-84d4-b75e9057f831)


https://github.com/derfurkan/OfflinePlayers/assets/87219200/9f911c28-8303-470f-ba14-7780a03eda1f


(video is blurry because i had it in a very small window to watch the console

**Comment by Daethatrex** [comment] 2023-06-09 16:05
I can confirm this happens for me as well.

Have not tried with just this plugin, but same issue! 

I am using 1.19.4 Purpur.

**Comment by derfurkan** [comment] 2023-06-09 16:48
I will investigate more and find a way to reproduce it on my side. If i found anything ill post it here.

**Comment by derfurkan** [comment] 2023-06-09 18:03
So after a few tries i could reproduce the issue and it seems like the clone is being undisguised when the chunk where he is located is unloaded. This issue is fixed by removing the clone if the chunk unloads and spawning him if the player joins.

Fix is pushed on SpigotMC: https://www.spigotmc.org/resources/offlineplayers-never-let-players-disappear.104985/updates

### **Thank you for reporting the issue and making OfflinePlayers better :)**
If there are not questions or problems this issue can be closed.

**Closed** 2023-06-11 21:26 UTC

**Comment by J-dotjs** [comment] 2023-06-26 01:53
wasnt fixed but whatever

**Comment by derfurkan** [comment] 2023-06-26 04:00
> wasnt fixed but whatever

Yep you were right. There was a case which i didn't cover. I checked on it again and fixed this issue it should work now.
Fix is pushed on SpigotMC: https://www.spigotmc.org/resources/offlineplayers-never-let-players-disappear.104985/

**Comment by J-dotjs** [comment] 2023-06-26 21:40
still doesnt work

**Comment by derfurkan** [comment] 2023-06-26 23:02
> still doesnt work

Nope tried it a few times now and worked every time. I used the reproduction steps you wrote in your original issue. 
Are you sure you are running everything on the latest version?

**Comment by J-dotjs** [comment] 2023-06-27 02:14
> 

Yeah I'm running all latest deleted all config for disguises plugin and protocol lib and this plugin and fresh installed, issue happens sometimes and doesn't other times

**Comment by derfurkan** [comment] 2023-06-27 04:54
> > 
> 
> Yeah I'm running all latest deleted all config for disguises plugin and protocol lib and this plugin and fresh installed, issue happens sometimes and doesn't other times

Just pushed a silent update to SpigotMC. Hopefully its now fixed since this issue is making me insane.
